# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."cloudflare-ddns" = {
    image = "oznu/cloudflare-ddns:latest";
    environment = {
      "API_KEY" = "oBT_2Nzuinz3yVDbECObLbeboVI29jnNRVV3Hu4S";
      "CRON" = "@hourly";
      "ZONE" = "lodgeserver.net";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=cloudflare-ddns"
      "--network=network_default"
    ];
  };
  systemd.services."docker-cloudflare-ddns" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-network_default.service"
    ];
    requires = [
      "docker-network-network_default.service"
    ];
    partOf = [
      "docker-compose-network-root.target"
    ];
    wantedBy = [
      "docker-compose-network-root.target"
    ];
  };
  virtualisation.oci-containers.containers."wg-easy" = {
    image = "ghcr.io/wg-easy/wg-easy";
    environment = {
      "LANG" = "en";
      "WG_DEFAULT_DNS" = "172.16.0.9";
      "WG_HOST" = "lodgeserver.net";
    };
    volumes = [
      "network_etc_wireguard:/etc/wireguard:rw"
    ];
    ports = [
      "51820:51820/udp"
      "51821:51821/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--cap-add=SYS_MODULE"
      "--network-alias=wg-easy"
      "--network=network_default"
      "--sysctl=net.ipv4.conf.all.src_valid_mark=1"
      "--sysctl=net.ipv4.ip_forward=1"
    ];
  };
  systemd.services."docker-wg-easy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-network_default.service"
      "docker-volume-network_etc_wireguard.service"
    ];
    requires = [
      "docker-network-network_default.service"
      "docker-volume-network_etc_wireguard.service"
    ];
    partOf = [
      "docker-compose-network-root.target"
    ];
    wantedBy = [
      "docker-compose-network-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-network_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f network_default";
    };
    script = ''
      docker network inspect network_default || docker network create network_default
    '';
    partOf = [ "docker-compose-network-root.target" ];
    wantedBy = [ "docker-compose-network-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-network_etc_wireguard" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect network_etc_wireguard || docker volume create network_etc_wireguard
    '';
    partOf = [ "docker-compose-network-root.target" ];
    wantedBy = [ "docker-compose-network-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-network-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
