# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."qbittorrent" = {
    image = "lscr.io/linuxserver/qbittorrent:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TORRENTING_PORT" = "6881";
      "TZ" = "Europe/London";
      "WEBUI_PORT" = "8080";
    };
    volumes = [
      "/home/dave/config/qbittorrent:/config:rw"
      "/mnt/media/downloads:/mnt/media/downloads:rw"
    ];
    dependsOn = [
      "torrent-gluetun"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:torrent-gluetun"
    ];
  };
  systemd.services."docker-qbittorrent" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-torrent-root.target"
    ];
    wantedBy = [
      "docker-compose-torrent-root.target"
    ];
  };
  virtualisation.oci-containers.containers."torrent-gluetun" = {
    image = "qmcgaw/gluetun";
    environment = {
      "SERVER_CITIES" = "Amsterdam";
      "VPN_SERVICE_PROVIDER" = "mullvad";
      "VPN_TYPE" = "wireguard";
      "WIREGUARD_ADDRESSES" = "10.65.185.50/32";
      "WIREGUARD_PRIVATE_KEY" = "KHfsoerIJghmgUVMJHYIGyN4Ue7sLzzjMXufx/wPTVY=";
    };
    ports = [
      "8080:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--device=/dev/net/tun:/dev/net/tun:rwm"
      "--network-alias=gluetun"
      "--network=torrent_default"
    ];
  };
  systemd.services."docker-torrent-gluetun" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-torrent_default.service"
    ];
    requires = [
      "docker-network-torrent_default.service"
    ];
    partOf = [
      "docker-compose-torrent-root.target"
    ];
    wantedBy = [
      "docker-compose-torrent-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-torrent_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f torrent_default";
    };
    script = ''
      docker network inspect torrent_default || docker network create torrent_default
    '';
    partOf = [ "docker-compose-torrent-root.target" ];
    wantedBy = [ "docker-compose-torrent-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-torrent-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
