services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080
      # - 6881:6881
      # - 6881:6881/udp
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=KHfsoerIJghmgUVMJHYIGyN4Ue7sLzzjMXufx/wPTVY=
      - WIREGUARD_ADDRESSES=10.65.185.50/32
      - SERVER_CITIES=Amsterdam

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/dave/config/qbittorrent:/config
      - /mnt/media/downloads:/mnt/media/downloads
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    restart: unless-stopped

