services:
  expressvpn:
    container_name: expressvpn
    image: polkaned/expressvpn
    environment:
      - ACTIVATION_CODE=EDNKUZKM5HKVXZ3E3JCHCKE
      - SERVER=Austria
    cap_add:
      - NET_ADMIN
    devices: 
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true
    ports:
      - 8080:8080       # qbittorrent
      - 6881:6881
      - 6881:6881/udp
      - 8191:8191       # flaresolverr
    restart: unless-stopped

  # qbittorrent:
  #   image: lscr.io/linuxserver/qbittorrent:latest
  #   container_name: qbittorrent
  #   network_mode: service:expressvpn
  #   depends_on: 
  #     - expressvpn
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #     - WEBUI_PORT=8080
  #   volumes:
  #     - /home/dave/config/qbittorrent:/config
  #     - /mnt/media:/media
  #   restart: unless-stopped

  # flaresolverr:
  #   image: ghcr.io/flaresolverr/flaresolverr:latest
  #   container_name: flaresolverr
  #   network_mode: service:expressvpn
  #   depends_on: 
  #     - expressvpn
  #   environment:
  #     - LOG_LEVEL=info
  #     - LOG_HTML=false
  #     - CAPTCHA_SOLVER=none
  #     - TZ=Europe/London
  #   restart: unless-stopped 
